
POST https://modern-noemi-rwooga3dservices-e96463f8.koyeb.app/auth/register/
Content-Type: application/json

{
    "email": "rugambagislain@gmail.com",
    "password": "Rugamba@123",
    "full_name": "Gislain RUGAMBA",
    "phone_number": "0780750980",
    "password_confirm": "Rugamba@123"
}

### Verify email
POST https://modern-noemi-rwooga3dservices-e96463f8.koyeb.app/auth/verify_email/
Content-Type: application/json

{
    "email": "gislain222007024@gmail.com",
    "otp": "435997"

}

### Login 
POST https://modern-noemi-rwooga3dservices-e96463f8.koyeb.app/auth/login/
Content-Type: application/json

{
    "email": "rugambagislain@gmail.com",
    "password": "Rugamba@123"
}